### ISSUE TITLE
Add reviewers on a Phabricator revision

### ISSUE THREAD

**Issue by La0** [mozilla/libmozdata#212]
Required for https://github.com/mozilla/code-review/issues/1475

We need a new method in the Phabricator API client class to add reviewers to a known revision.

This require 2 steps:
1. retrieving the PHID of a group of users by hitting `project.search`
2. using that PHID in `differential.revision.edit` with a transaction type of `reviewers.add`

More details on the [original issue](https://github.com/mozilla/code-review/issues/1475#issuecomment-1446277094).

**Comment by EvaBardou** [comment]
> retrieving the PHID of a group of users by hitting project.search

`PhabricatorAPI.search_projects()` already exists :tada: 

> using that PHID in differential.revision.edit with a transaction type of reviewers.add

In the end, we'll just add a generic method to edit a differential revision instead and take care of retrieving the reviewers group PHID in **code-review-bot** before calling `PhabricatorAPI.edit_revision()` with a `reviewers.add` transaction.
