### ISSUE TITLE
Enforce setting a user agent

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozdata#222]
So services to which users of this library connect to can identify them.

**Comment by marco-c** [comment]
We could replace all `config.get("User-Agent", "name", "libmozdata")` with `config.get("User-Agent", "name")` and assert the result is not None (or add a new function in config which fails if there's no value for a key).

**Comment by marco-c** [comment]
@mlbonhomme could you take this on?

**Comment by mlbonhomme** [comment]
Sure!
