### ISSUE TITLE
Make sure all requests are setting a user agent

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozdata#223]
E.g. we are not setting it at https://github.com/mozilla/libmozdata/blob/aa80079c9a036531606942e175a25400fa69cfe3/libmozdata/phabricator.py#LL50C5-L50C31.

**Comment by suhaibmujahid** [comment]
See #224

**Comment by marco-c** [comment]
@suhaibmujahid that was an example, but there are other requests without UA.

**Comment by La0** [comment]
We'll work on this as a good first patch for our new contributor from Teklia
