### ISSUE TITLE
Drop the `revision_exists_on_central` function

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/libmozdata#224]
If it isn't used anywhere we could remove it.

_Originally posted by @marco-c in https://github.com/mozilla/libmozdata/issues/219#issuecomment-1533734387_

**Comment by suhaibmujahid** [comment]
It does not seem to be used currently by any public repository on GitHub: https://github.com/search?q=revision_exists_on_central&type=code


Historically, it was used in Release Services: https://github.com/mozilla/release-services/blob/e0ccf493f1a7a94994b963d3fc54449d19faf89d/src/codecoverage/backend/codecoverage_backend/api.py#LL83C1-L83C66.

**Comment by marco-c** [comment]
Let's get rid of it!
