### ISSUE TITLE
Use json-mozbuildinfo service of hg.mozilla.org to get module info given a path

### ISSUE THREAD

**Issue by marco-c** [mozilla/libmozdata#53]
More details: https://bugzilla.mozilla.org/show_bug.cgi?id=1297966.

https://bugzilla.mozilla.org/show_bug.cgi?id=1263973 should be fixed first.

This should work better than our current approach of parsing the contents of the page https://wiki.mozilla.org/Modules/All.

**Comment by willkg** [comment]
Per this bug, json-mozbuildinfo was removed: https://bugzilla.mozilla.org/show_bug.cgi?id=1523745

I don't see any evidence that got replaced by something else, so I think this should get closed out.

**Comment by marco-c** [comment]
Agreed, let's do #180 instead.
